[info]
url = "https://bendancom.github.io"  # Site URL
subroot = "Blog"
icon = "/assets/image/favicon.ico"
avatar = "/assets/image/avatar.png"
defaultLanguage = "zh"

[SEO]
google = { name = "google-site-verification", key = "pwaT5WWNlN9GKBzYINHWt83Pst12qFw3kwEzVwpxyeQ" }
bing = { name = "msvalidate.01", key = "4056CAD5A32658E06A7A7E90B6D8C3B6" }

[social]
email = "bendancom@qq.com"  # Author email
bilibili = "https://space.bilibili.com/43229292"
github = "https://github.com/Bendancom"

[comment]
repo = "bendancom/Blog"
repoId = "R_kgDOSDaOzg"
repoCategory="Announcements"
repoCategoryId="DIC_kwDOSDaOzs4C66D5"
mapping="title"
strict="0"
reactionEnabled="1"
emitMetadata="0"
inputPosition="top"
loading="lazy"
crossorigin="anonymous"

[copyright]
sign = "©"
year = 2026
license = "CC BY-NC-SA 4.0"
url = "https://creativecommons.org/licenses/by-nc-sa/4.0/"
