[config.zh]
siteTitle = "岑白的博客"
siteAuthor = "岑白"
siteDescription = "岑白(Bendancom) 的博客"
siteBiography = ""
home = "主页"
archive = "归档"
about = "关于"
category = "分类"
tag = "标签"
tags = "标签"
find="查找"
feed = "订阅"
themeHue = "主题色"
light = "亮色"
dark = "暗色"
system = "跟随系统"
languageShortName = "中"
languageName = "简体中文"
single = "单篇"
singleShort = "单"
series = "系列"
seriesShort = "系"
all = "全部"
allShort = "全"
title = "标题"
author = "作者"
subtitle = "副标题"
date = "日期"
and = "与"
abbrList = "缩写词表"
symbolList = "符号表"

[abbr.zh]
PDE = "偏微分方程"

[symbol.zh]
Force = "力"
Mass = "质量"

[config.en]
siteTitle = "Bendancom's blog"
siteAuthor = "Bendancom"
siteDescription = "Bendancom(岑白)'s blog'"
siteBiography = ""
home = "Home"
archive = "Archive"
about = "About"
category = "Categories"
tag = "Tag"
tags = "Tags"
find="Find"
feed = "Feed"
themeHue = "Theme Hue"
light = "Light"
dark = "Dark"
system = "System"
languageShortName = "En"
languageName = "English"
single = "Single"
singleShort = "Sgl"
series = "Series"
seriesShort = "Ser"
all = "All"
allShort = "All"
title = "Title"
author = "Author"
subtitle = "Subtitle"
and = "and"
date = "Date"
abbrList = "List of Abbreviations"
symbolList = "List of Symbol"

[abbr.en]
PDE = "Partial Differential Equation"

[symbol.en]
Force = "Force"
Mass = "Mass"
